version: '3.4'

services:

  postgres13:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB= sales_payments
    ports:
      - "5501:5432"
    volumes:
      - postgres13:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: always
    entrypoint: redis-server --appendonly yes
    ports:
      - "6401:6379"
    volumes:
      - redis:/data

volumes:
  postgres13:
    driver: local
  redis:
    driver: local

  
    
